SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS AS d
WHERE d.SKILL_CODE &
(
SELECT s.CODE
FROM SKILLCODES AS s
WHERE s.NAME = 'Python'
)
OR d.SKILL_CODE &
(
SELECT s.CODE
FROM SKILLCODES AS s
WHERE s.NAME = 'C#'
)
ORDER BY d.ID ASC;