-- 조회수가 가장 높은 중고거래 게시물 -> 첨부파일 경로(FILE ID 기준 내림차순 정렬)
-- 파일 기본 경로 /hone/grep/src/BOARD_ID/FILE_ID FILE_NAME FILE_EXT
SELECT CONCAT("/home/grep/src/", B.BOARD_ID, "/", B.FILE_ID, B.FILE_NAME, B.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS A 
JOIN USED_GOODS_FILE AS B 
ON A.BOARD_ID = B.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY B.FILE_ID DESC;